const express = require('express');
const axios = require('axios');
const app = express();
app.use(express.json());
const API_KEY = process.env.WHATSAPP_API_KEY;
const GARY_1 = process.env.GARY_NUMBER_1;
const GARY_2 = process.env.GARY_NUMBER_2;
const RODRIGO = process.env.RODRIGO_NUMBER;
const PORT = process.env.PORT || 3000;
const BASE_URL = 'https://waba-v2.360dialog.io/messages';
const PRESUPUESTOS = {'penaflo':{nombre:'Peñaflor',etapas:{'E1':{nombre:'Etapa 1',ppto:34233724},'E2':{nombre:'Etapa 2',ppto:42792155},'E3':{nombre:'Etapa 3',ppto:51350587},'E4':{nombre:'Etapa 4',ppto:42792158}}},'codegua':{nombre:'Codegua',etapas:{'E1':{nombre:'Etapa 1',ppto:57590086},'E2':{nombre:'Etapa 2',ppto:79445467},'E3':{nombre:'Etapa 3',ppto:64701881},'E4':{nombre:'Etapa 4',ppto:84515200}}},'rancagua':{nombre:'Rancagua',etapas:{'E1':{nombre:'Etapa 1',ppto:23000000},'E2':{nombre:'Etapa 2',ppto:28000000},'E3':{nombre:'Etapa 3',ppto:32000000},'E4':{nombre:'Etapa 4',ppto:41000000}}}};
const gastos={};const sesiones={};
function fmtMonto(n){return '$'+Math.round(n).toLocaleString('es-CL');}
function getGastadoEtapa(o,e){if(!gastos[o]||!gastos[o][e])return 0;return gastos[o][e].reduce((s,g)=>s+g.monto,0);}
async function enviarMensaje(numero,texto){try{await axios.post(BASE_URL,{messaging_product:'whatsapp',to:numero,type:'text',text:{body:texto}},{headers:{'D360-API-KEY':API_KEY,'Content-Type':'application/json'}});}catch(err){console.error('Error:',err.response?.data||err.message);}}
function esAutorizado(n){return[GARY_1,GARY_2,RODRIGO].includes(n);}
function esGary(n){return[GARY_1,GARY_2].includes(n);}
function parsearMensaje(texto){const p=texto.split('/').map(x=>x.trim());if(p.length>=4){const oR=p[0].toLowerCase();const eR=p[1].toUpperCase();const prov=p[2];const m=parseInt(p[3].replace(/\./g,'').replace(/\$/g,''));const desc=p[4]||'';let oId=null;if(oR.includes('pen')||oR.includes('islevy')||oR.includes('maribel'))oId='penaflo';else if(oR.includes('cod')||oR.includes('mardon'))oId='codegua';else if(oR.includes('ran')||oR.includes('adela')||oR.includes('camilo'))oId='rancagua';if(oId&&eR.match(/E[1-4]/)&&!isNaN(m)&&m>0)return{obraId:oId,etapaId:eR,proveedor:prov,monto:m,desc};}return null;}
function registrarGasto(o,e,g){if(!gastos[o])gastos[o]={};if(!gastos[o][e])gastos[o][e]=[];gastos[o][e].push({...g,fecha:new Date().toLocaleDateString('es-CL')});}
function resumenEtapa(o,e){const ob=PRESUPUESTOS[o];const et=ob.etapas[e];const g=getGastadoEtapa(o,e);const s=et.ppto-g;const p=Math.round((g/et.ppto)*100);const sem=p>90?'🔴':p>75?'🟡':'🟢';return`📊 *${ob.nombre} — ${et.nombre}*\nPresupuesto: ${fmtMonto(et.ppto)}\nGastado: ${fmtMonto(g)} (${p}%)\nSaldo: ${fmtMonto(s)} ${sem}`;}
function resumenEmpresa(){let r=`📋 *Resumen SINAN — ${new Date().toLocaleDateString('es-CL')}*\n\n`;for(const[oId,ob]of Object.entries(PRESUPUESTOS)){let tp=0,tg=0;for(const eId of Object.keys(ob.etapas)){tp+=ob.etapas[eId].ppto;tg+=getGastadoEtapa(oId,eId);}const p=Math.round((tg/tp)*100);const em=p>90?'🔴':p>75?'🟡':'🟢';r+=`${em} *${ob.nombre}*: ${fmtMonto(tg)} / ${fmtMonto(tp)} (${p}%)\n`;}r+=`\nGastos fijos mes: ${fmtMonto(13018806)}`;return r;}
app.post('/webhook',async(req,res)=>{res.sendStatus(200);try{const msgs=req.body?.entry?.[0]?.changes?.[0]?.value?.messages;if(!msgs||msgs.length===0)return;const msg=msgs[0];const num=msg.from;const txt=msg.text?.body?.trim();if(!txt||!esAutorizado(num))return;const tl=txt.toLowerCase();if(tl==='resumen'||tl==='estado'){await enviarMensaje(num,resumenEmpresa());return;}if(tl==='ayuda'||tl==='help'){await enviarMensaje(num,`📌 *Comandos SINAN Bot*\n\n*Registrar gasto:*\nOBRA / ETAPA / PROVEEDOR / MONTO / DESCRIPCION\n\n*Ejemplo:*\nCodegua / E1 / Yolito / 1166311 / Fierros\n\n*Obras:* Peñaflor, Codegua, Rancagua\n*Etapas:* E1, E2, E3, E4\n\n*Comandos:*\n• resumen — Estado empresa\n• ayuda — Este mensaje`);return;}const g=parsearMensaje(txt);if(g){const ob=PRESUPUESTOS[g.obraId];const et=ob.etapas[g.etapaId];const gD=getGastadoEtapa(g.obraId,g.etapaId)+g.monto;const sal=et.ppto-gD;if(gD>et.ppto){const exc=gD-et.ppto;sesiones[GARY_1]={tipo:'aprobacion',gasto:g,numero:num};sesiones[GARY_2]={tipo:'aprobacion',gasto:g,numero:num};const al=`🔴 *ALERTA SOBRECOSTO*\n${ob.nombre} — ${et.nombre}\nGasto: ${fmtMonto(g.monto)} (${g.proveedor})\nExceso: ${fmtMonto(exc)}\n\n¿Apruebas?\nSI — aprobar\nNO — rechazar`;await enviarMensaje(GARY_1,al);if(GARY_2!==GARY_1)await enviarMensaje(GARY_2,al);await enviarMensaje(num,`⚠️ Enviado a Gary para aprobación — supera presupuesto.`);return;}registrarGasto(g.obraId,g.etapaId,g);const conf=`✅ *Registrado*\n${ob.nombre} — ${et.nombre}\nProveedor: ${g.proveedor}\nMonto: ${fmtMonto(g.monto)}\n${g.desc?`Descripción: ${g.desc}\n`:''}\n${resumenEtapa(g.obraId,g.etapaId)}`;await enviarMensaje(num,conf);if(!esGary(num)){const ng=`💰 *Nuevo gasto*\n${ob.nombre} — ${et.nombre}\n${g.proveedor}: ${fmtMonto(g.monto)}\nSaldo: ${fmtMonto(sal)}`;await enviarMensaje(GARY_1,ng);if(GARY_2!==GARY_1)await enviarMensaje(GARY_2,ng);}return;}if(sesiones[num]){const ses=sesiones[num];const r=tl;if(r==='si'||r==='sí'||r.includes('✅')){registrarGasto(ses.gasto.obraId,ses.gasto.etapaId,ses.gasto);await enviarMensaje(num,`✅ Aprobado.\n${resumenEtapa(ses.gasto.obraId,ses.gasto.etapaId)}`);await enviarMensaje(ses.numero,`✅ Gary aprobó ${fmtMonto(ses.gasto.monto)}.`);delete sesiones[GARY_1];delete sesiones[GARY_2];}else if(r==='no'||r.includes('❌')){await enviarMensaje(num,`❌ Rechazado.`);await enviarMensaje(ses.numero,`❌ Gary rechazó el gasto.`);delete sesiones[GARY_1];delete sesiones[GARY_2];}return;}await enviarMensaje(num,`No entendí. Escribe *ayuda* para ver el formato.`);}catch(err){console.error('Error webhook:',err);}});
app.get('/',(req,res)=>{res.json({status:'SINAN Bot activo',timestamp:new Date().toISOString()});});
app.listen(PORT,()=>{console.log(`SINAN Bot corriendo en puerto ${PORT}`);});
